spring:
  application:
    name: store
    port: 8000
  datasource:
    url: jdbc:mysql://localhost:3309/store?createDatabaseIfNotExist=true
    username: root
    password: root_password
app.page-size: 10